package com.curamatrix.hsm.service;

import lombok.extern.slf4j.Slf4j;
import org.springframework.scheduling.annotation.Scheduled;
import org.springframework.stereotype.Service;
import org.springframework.web.servlet.mvc.method.annotation.SseEmitter;

import java.io.IOException;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.concurrent.ConcurrentHashMap;

/**
 * Manages tenant-scoped SSE emitters for real-time queue update notifications.
 *
 * When a doctor checks in or checks out a patient, this service broadcasts a
 * lightweight "QUEUE_UPDATED" event to all connected receptionist browsers
 * belonging to the same tenant. The frontend then re-fetches the queue dashboard.
 *
 * Thread-safe: uses ConcurrentHashMap at both levels (outer: tenantId, inner: clientId).
 * Tenant isolation: Hospital A's events are never delivered to Hospital B's receptionists.
 */
@Slf4j
@Service
public class QueueEventService {

    // Outer key: tenantId, Inner key: clientId (UUID from frontend)
    private final Map<Long, Map<String, SseEmitter>> emittersByTenant = new ConcurrentHashMap<>();

    /**
     * Registers a new SSE emitter for a connected client, scoped to the given tenant.
     *
     * @param tenantId the tenant this client belongs to
     * @param clientId a UUID generated by the frontend browser tab
     * @return the registered SseEmitter (returned directly from the controller)
     */
    public SseEmitter register(Long tenantId, String clientId) {
        // 30-minute timeout; EventSource auto-reconnects on timeout/error
        SseEmitter emitter = new SseEmitter(30 * 60 * 1000L);

        emitter.onCompletion(() -> removeEmitter(tenantId, clientId, "completion"));
        emitter.onTimeout(()   -> removeEmitter(tenantId, clientId, "timeout"));
        emitter.onError(ex     -> removeEmitter(tenantId, clientId, "error: " + (ex != null ? ex.getMessage() : "unknown")));

        emittersByTenant
                .computeIfAbsent(tenantId, k -> new ConcurrentHashMap<>())
                .put(clientId, emitter);

        log.debug("SSE client registered: tenant={}, client={} (tenant total: {})",
                tenantId, clientId, getConnectedClientCount(tenantId));

        // Send initial "connected" event so the client knows the stream is live
        try {
            emitter.send(SseEmitter.event()
                    .name("connected")
                    .data("{\"status\":\"connected\",\"clientId\":\"" + clientId + "\"}"));
        } catch (IOException e) {
            removeEmitter(tenantId, clientId, "initial-send-failed");
        }

        return emitter;
    }

    /**
     * Broadcasts a QUEUE_UPDATED event to all connected clients of the given tenant.
     * Called by PatientService after check-in or check-out.
     *
     * @param tenantId the tenant whose receptionists should be notified
     * @param doctorId the doctor whose queue changed
     */
    public void broadcastQueueUpdate(Long tenantId, Long doctorId) {
        Map<String, SseEmitter> tenantEmitters = emittersByTenant.get(tenantId);
        if (tenantEmitters == null || tenantEmitters.isEmpty()) {
            log.debug("No SSE clients connected for tenant={}, skipping broadcast", tenantId);
            return;
        }

        // Use LocalDateTime.toString() — NOT Jackson default (which serializes to array)
        String timestamp = LocalDateTime.now().toString();
        // Use string concatenation (not Map.of) to avoid null-value NPE per AGENTS.md
        String payload = "{\"type\":\"QUEUE_UPDATED\",\"doctorId\":" + doctorId
                + ",\"tenantId\":" + tenantId
                + ",\"timestamp\":\"" + timestamp + "\"}";

        log.debug("Broadcasting QUEUE_UPDATED: tenant={}, doctorId={}, clients={}",
                tenantId, doctorId, tenantEmitters.size());

        // Collect stale emitters to remove after iteration (avoid ConcurrentModificationException)
        List<String> staleClients = new ArrayList<>();

        tenantEmitters.forEach((clientId, emitter) -> {
            try {
                emitter.send(SseEmitter.event()
                        .name("queue-update")
                        .data(payload));
            } catch (IOException e) {
                staleClients.add(clientId);
                log.debug("Removed stale SSE emitter: tenant={}, client={}", tenantId, clientId);
            }
        });

        staleClients.forEach(clientId -> tenantEmitters.remove(clientId));
    }

    /**
     * Sends a heartbeat to all connected clients across all tenants every 25 seconds.
     * Prevents intermediate proxies (nginx, AWS ALB) from closing idle connections.
     */
    @Scheduled(fixedDelay = 25000)
    public void sendHeartbeat() {
        if (emittersByTenant.isEmpty()) return;

        long ts = System.currentTimeMillis();
        String payload = "{\"ts\":" + ts + "}";

        emittersByTenant.forEach((tenantId, tenantEmitters) -> {
            List<String> staleClients = new ArrayList<>();
            tenantEmitters.forEach((clientId, emitter) -> {
                try {
                    emitter.send(SseEmitter.event()
                            .name("heartbeat")
                            .data(payload));
                } catch (IOException e) {
                    staleClients.add(clientId);
                    log.debug("Heartbeat: removed stale emitter tenant={}, client={}", tenantId, clientId);
                }
            });
            staleClients.forEach(clientId -> tenantEmitters.remove(clientId));
        });
    }

    /** Returns the number of currently connected SSE clients for a given tenant. */
    public int getConnectedClientCount(Long tenantId) {
        Map<String, SseEmitter> tenantEmitters = emittersByTenant.get(tenantId);
        return tenantEmitters == null ? 0 : tenantEmitters.size();
    }

    private void removeEmitter(Long tenantId, String clientId, String reason) {
        Map<String, SseEmitter> tenantEmitters = emittersByTenant.get(tenantId);
        if (tenantEmitters != null) {
            tenantEmitters.remove(clientId);
            log.debug("SSE client removed ({}): tenant={}, client={}", reason, tenantId, clientId);
        }
    }
}
