package com.curamatrix.hsm.controller;

import com.curamatrix.hsm.context.TenantContext;
import com.curamatrix.hsm.dto.response.DashboardStatsResponse;
import com.curamatrix.hsm.dto.response.QueueDashboardResponse;
import com.curamatrix.hsm.dto.response.QueueEntryResponse;
import com.curamatrix.hsm.service.QueueEventService;
import com.curamatrix.hsm.service.QueueService;
import io.swagger.v3.oas.annotations.tags.Tag;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.util.StringUtils;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.servlet.mvc.method.annotation.SseEmitter;

import java.util.List;
import java.util.UUID;

@Slf4j
@RestController
@RequestMapping("/api/queue")
@RequiredArgsConstructor
@Tag(name = "5. Queue", description = "Real-time queue management for receptionist and doctor")
public class QueueController {

    private final QueueService queueService;
    private final QueueEventService queueEventService;

    @GetMapping("/today")
    @PreAuthorize("hasAnyRole('RECEPTIONIST', 'ADMIN')")
    public ResponseEntity<List<QueueEntryResponse>> getTodayQueue() {
        return ResponseEntity.ok(queueService.getTodayQueue());
    }

    @GetMapping("/doctor/{doctorId}/today")
    @PreAuthorize("hasAnyRole('RECEPTIONIST', 'DOCTOR', 'ADMIN')")
    public ResponseEntity<List<QueueEntryResponse>> getDoctorQueue(@PathVariable Long doctorId) {
        return ResponseEntity.ok(queueService.getDoctorQueue(doctorId));
    }

    @GetMapping("/dashboard")
    @PreAuthorize("hasAnyRole('RECEPTIONIST', 'ADMIN')")
    public ResponseEntity<DashboardStatsResponse> getDashboardStats() {
        return ResponseEntity.ok(queueService.getDashboardStats());
    }

    /**
     * Rich queue dashboard — powers the new Queue Management UI.
     * Returns all data needed for the full page in a single call.
     *
     * @param doctorId optional — if provided, the waiting queue is scoped to this doctor
     */
    @GetMapping("/queue-dashboard")
    @PreAuthorize("hasAnyRole('RECEPTIONIST', 'ADMIN')")
    public ResponseEntity<QueueDashboardResponse> getQueueDashboard(
            @RequestParam(required = false) Long doctorId) {
        return ResponseEntity.ok(queueService.getQueueDashboard(doctorId));
    }

    public record NotifyDoctorRequest(Long appointmentId, Long doctorId, String patientName) {}

    /**
     * Notify a doctor that the receptionist is calling a patient for them.
     */
    @PostMapping("/notify-doctor")
    @PreAuthorize("hasAnyRole('RECEPTIONIST', 'ADMIN')")
    public ResponseEntity<Void> notifyDoctor(@RequestBody NotifyDoctorRequest request) {
        Long tenantId = TenantContext.getTenantId();
        queueEventService.broadcastDoctorCallRequest(
                tenantId, request.doctorId(), request.appointmentId(), request.patientName());
        return ResponseEntity.ok().build();
    }

    /**
     * SSE stream endpoint — browsers connect here to receive real-time queue-update events.
     *
     * Authentication: JWT is accepted via ?token= query param because the browser's
     * native EventSource API cannot set custom headers.
     *
     * @param token    JWT token (from ?token= query param; TenantInterceptor sets TenantContext)
     * @param clientId UUID identifying this browser tab (generated by frontend; auto-generated if blank)
     */
    @GetMapping(value = "/events", produces = MediaType.TEXT_EVENT_STREAM_VALUE)
    @PreAuthorize("hasAnyRole('RECEPTIONIST', 'ADMIN', 'DOCTOR')")
    public SseEmitter subscribeToQueueEvents(
            @RequestParam(required = false) String token,
            @RequestParam(defaultValue = "") String clientId) {

        Long tenantId = TenantContext.getTenantId();
        String resolvedClientId = StringUtils.hasText(clientId) ? clientId : UUID.randomUUID().toString();

        log.info("SSE subscription: tenant={}, client={}", tenantId, resolvedClientId);
        return queueEventService.register(tenantId, resolvedClientId);
    }
}
